services:

  flask:
    image: 'ihayhurst/tlmweather:latest'
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - FLASK_DEBUG=1
      - TEMPLATES_AUTO_RELOAD=1
      - APP_NAME=WeatherReport
      - TZ=Europe/London
    volumes:
      - './flask:/app'
      - './data-log/:/app/app/website/data-log'
    expose:
      - 8080

  log:
    build: ./rpi-gpio
    container_name: rpi-gpio
    volumes:
      - './data-log/:/data-log/'
    devices:
      - '/dev/i2c-1:/dev/i2c-1'
    ports:
      - '5000:5000'
    restart: always

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - '80:80'

 # redis:
 #   image: redis
 #   container_name: redis
 #   restart: always
 #   sysctls:
 #     net.core.somaxconn: "1024"

volumes:
  app: {}
