
services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
#    depends_on:
#      - redis
    environment:
      - FLASK_ENV=development
      - APP_NAME=WeatherReport
    volumes:
      - ./flask/app:/app/app
      - ./data-log/:/app/app/website/data-log
    expose:
      - 8080

  log:
    build: ./rpi-gpio
    container_name: rpi-gpio
    volumes:
      - ./data-log/:/data-log/
    devices:
      - "/dev/i2c-1:/dev/i2c-1"
    restart: always 
      
  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

#  redis:
#    image: redis

volumes:
    app: {}
